library(org.Hs.eg.db)
library(data.table)
keys <- keys(org.Hs.eg.db)
Gene_GO_Information<-AnnotationDbi::select(org.Hs.eg.db, keys=keys, column=c("SYMBOL","GOALL","ENSEMBL"), keytype="ENTREZID")
setDT(Gene_GO_Information, keep.rownames = "SI")
write.table(Gene_GO_Information,file="Gene_GO_Information_org.Hs.eg.db.txt",sep = "\t",row.names = F)
sessionInfo()